### PR TITLE
[Bugfix] Chat bug fixes for layout, skip messages button, keyboard, and message input

### PR DESCRIPTION
**Pull request by palatter**
## Purpose

* Resolved issue with message bubble font colors
* Resolved issue with skip messages button having multiple lines of text
* Resolved issue with skip messages button missing drop shadow
* Resolved issue with skip messages button not having a correct radius on corners
* Resolved issue with skip messages button label being plural
* Resolved issue with keyboard not having multiline support
* Resolved issue with keyboard not having a return button
* Resolved issue with keyboard not dismissing when tapping the screen

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Pull request checklist

This PR has considered:
- [ ] Color Theming
- [ ] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] View Data Injection
- [ ] Demo App UI/UX update

## How to Test

* Open...
* Click on...

## What to Check

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| Screenshot or description before this change | Screenshot or description with this change |

### CODE REVIEW

**Comment by Leah-Xia-Microsoft** [comment]
Haven't look into the code yet, just testing and find some issues that's not in the last bug bash
1. New message button doesn't scroll the view
https://user-images.githubusercontent.com/107075081/203446812-96e37fac-4178-4f03-9645-2ed20d457263.MP4
2. In figma design, we use p.m. format for the time instead of PM
3. The last message touches the input view

4. Typing indicator is a bit covered by the input view

**Comment by palatter** [comment]
> Haven't look into the code yet, just testing and find some issues that's not in the last bug bash
> 
> 1. New message button doesn't scroll the view
>    https://user-images.githubusercontent.com/107075081/203446812-96e37fac-4178-4f03-9645-2ed20d457263.MP4
> 2. In figma design, we use p.m. format for the time instead of PM
> 3. The last message touches the input view
> 
> 
> 
> 4. Typing indicator is a bit covered by the input view
> 

Oh good catch, thanks!

Seems all behavior that relies on scrolling jumping to the bottom doesn't work after the latest merge with feature/chat. Have you seen any similar behavior in your branches?

**Comment by Leah-Xia-Microsoft** [comment]
> > Haven't look into the code yet, just testing and find some issues that's not in the last bug bash
> > 
> > 1. New message button doesn't scroll the view
> >    https://user-images.githubusercontent.com/107075081/203446812-96e37fac-4178-4f03-9645-2ed20d457263.MP4
> > 2. In figma design, we use p.m. format for the time instead of PM
> > 3. The last message touches the input view
> > 
> > 
> > 
> > 4. Typing indicator is a bit covered by the input view
> > 
> > 
> 
> @Leah-Xia-Microsoft
> 
> Oh good catch, thanks!
> 
> Seems all behavior that relies on scrolling jumping to the bottom doesn't work after the latest merge with feature/chat. Have you seen any similar behavior in your branches?

It is this line 
` MessageView(viewModel: messageViewModel)
      .id(UUID())`
It use to be `.id(index)`
However, i need this change to re-render the view when message's sendStatus changes.

**Review by jimchou-dev — APPROVED** [review]
Skip button dont work but most likely due to the UUID for messageListView.
Also good call out on how to localize time, but that will be a future problem to deal with.

**Pull request merged**
