### PR TITLE
[Bugfix] Fix video and screen share

### PR DESCRIPTION
**Pull request by vhuseinova-msft**
## Purpose

* Revert changes from [PR #88](https://github.com/Azure/communication-ui-library-ios/pull/88/files)

## Does this introduce a breaking change?

```
[] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

## What to Check

- Participants grid and videos are rendered correctly on the Call screen
- Local video is displayed on the Setup and Calling screens
- Screensharing works as expected

### CODE REVIEW

**Review by AmyL219 — APPROVED** [review]
Are we using the `git revert` command?
https://opensource.com/article/18/6/git-reset-revert-rebase-commands

**Review by JoshuaLai — APPROVED** [review]
Just a simple revert. We can stress test this some more.

**Comment by vhuseinova-msft** [comment]
> Are we using the `git revert` command?
> https://opensource.com/article/18/6/git-reset-revert-rebase-commands

no, just returned code back. I havn't done revert as it removes the part of a branch history that contained the commits that were undone.
FYI @AmyL219 , @JoshuaLai

**Review by jimchou-dev — APPROVED** [review]
Tested with 3 users can see screenshare

**Review by kevinyulu — APPROVED** [review]

**Pull request merged**
