### PR TITLE
[Refactor] Improve bridging RendererView into SwiftUI

### PR DESCRIPTION
**Pull request by vhuseinova-msft**
## Purpose

* Added VideoRendererUIView for correct bridging RendererView into SwiftUI
* Removed the workaround in ParticipantGridCellView

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

## What to Check
Verify that the following are valid
* Participants grid and videos are rendered correctly on the Call screen
* Local video is displayed on the Setup and Calling screens

### CODE REVIEW

**Review by kevinyulu — COMMENTED** [review]
Tested in iPhone XR iOS 15.3.1. The video shows in portrait. For some reason when I switch to landscape, the app is not responding on my device.

**Review by AmyL219 — COMMENTED** [review]
I tried the constraints to resizing the rendererView, but it would caused the renderView failed in rendering in the old branch. 
So had to call `update(rendererView)` to resize the view manually by assigning frame. And we have to update the frame even if the `self.rendererView == rendererView`. Because the size of the VideoRenderView would be update by calling `UpdateUIView` and we need to update the frame manually every-time when the size change. 
But this would cause another issue which I have described inside the [document]([SwiftUIParticipantVideoRenderView.docx](https://microsoft-my.sharepoint-df.com/:w:/p/longamy/ETZauZ84HjxFrxoJDQvRp2UBLMAx1YQWk7FxRgH1dDrIxg?e=R3LcgY&isSPOFile=1&OR=Teams-HL&CT=1647905713375&params=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyOC8yMjAzMDcwMTYxMCJ9)).

**Comment by vhuseinova-msft** [comment]
> I tried the constraints to resizing the rendererView, but it would caused the renderView failed in rendering in the old branch.
> So had to call `update(rendererView)` to resize the view manually by assigning frame. And we have to update the frame even if the `self.rendererView == rendererView`. Because the size of the VideoRenderView would be update by calling `UpdateUIView` and we need to update the frame manually every-time when the size change.
> But this would cause another issue which I have described inside the document.

@AmyL219 yes, I've removed the constraints usage after the @kevinyulu'c comment and changed it to autoresizingMask that should guarantee that the view will be resized as expected. In this case, I think we shouldn't set frame once more when self.rendererView == rendererView.
Also, this solution is not the same as was implemented in DebugRenderView branch so I haven't got the same issue with the gray view that isn't updated to the video.  Please let me know if you will notice any issues with the layout after the last commit.

**Comment by AmyL219** [comment]
For autoresizingMask, it updates the subviews when it's bounds updated, see the [AutoresizingMask](https://developer.apple.com/documentation/uikit/uiview/1622559-autoresizingmask). So in this case, we should set the `VideoRendererUIView` autoresizing mask, because we want it resize the renderView which is the subview of `VideoRendererUIView`

in my test observation, the gridView would call `makeUIview` to make a new `VideoRendererUIView` whenever the resizing is happening. Not sure if autoresizing mask is working. I think we still need to test the scenario when `makeUIview` is not called but `updateUIView` is called for renderView resizing though.

**Comment by vhuseinova-msft** [comment]
> For autoresizingMask, it updates the subviews when it's bounds updated, see the [AutoresizingMask](https://developer.apple.com/documentation/uikit/uiview/1622559-autoresizingmask). So in this case, we should set the `VideoRendererUIView` autoresizing mask, because we want it resize the renderView which is the subview of `VideoRendererUIView`
> 
> in my test observation, the gridView would call `makeUIview` to make a new `VideoRendererUIView` whenever the resizing is happening. Not sure if autoresizing mask is working. I think we still need to test the scenario when `makeUIview` is not called but `updateUIView` is called for renderView resizing though.

As per documentation, we don't have to update the superview as we need to set this only for our subview and the subview will be updated when bounds for the superview is changed. 

 `updateUIView` is called a couple of times (1 after makeUIview with frame = .zero and other times without makeUIview but with updates to frame) when there are a lot of participants and:
1) a participant, that is not present on the grid, starts to talk
2) screen orientation is changed

I've tested both cases on iPhone 13 mini and a couple of simulators, and haven't noticed any differences in UI when` self.rendererView?.frame = frame` is added when `self.rendererView == rendererView` or not.

**Review by AmyL219 — APPROVED** [review]
Okey, I haven't seen issue in my local testing. Let's keep an eye on this in the bug bash.

**Review by kevinyulu — APPROVED** [review]
tested, LGTM

**Pull request merged**
