### PR TITLE
[Feature] Bumping minimum target to iOS 14

### PR DESCRIPTION
**Pull request by JoshuaLai**
## Purpose
Updating minimum taget to iOS 14

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What to Check
Full regression test is needed

### CODE REVIEW

**Review by palatter — COMMENTED** [review]
We should update the podspec in root as well with new min version.

**Comment by AmyL219** [comment]
Should we start a thread with Jorge about the update in the channel, to make sure we are admitted for minimum version bumping

**Comment by JoshuaLai** [comment]
> We should update the podspec in root as well with new min version.

Good catch. Updated!

**Comment by JoshuaLai** [comment]
> Should we start a thread with Jorge about the update in the channel, to make sure we are admitted for minimum version bumping

For sure. Maybe I can revert this to a draft for now so it is not accidentally merged

**Review by vhuseinova-msft — CHANGES_REQUESTED** [review]
Could you also update accessibility functions usage from
`accessibility(<parameterName>:)` to `accessibility< parameterName >`? [As Apple has added updated functions](https://developer.apple.com/documentation/swiftui/modifiedcontent/accessibilityhidden(_:)-3g7oh) with iOS 14 and as we don't need to support iOS 13 anymore we can update those methods. 
For example:
`accessibility(hidden:)` -> `accessibilityHidden(_:)`

**Comment by vhuseinova-msft** [comment]
> > Could you also update accessibility functions usage from `accessibility(<parameterName>:)` to `accessibility< parameterName >`? [As Apple has added updated functions](https://developer.apple.com/documentation/swiftui/modifiedcontent/accessibilityhidden(_:)-3g7oh) with iOS 14 and as we don't need to support iOS 13 anymore we can update those methods. For example: `accessibility(hidden:)` -> `accessibilityHidden(_:)`
> 
> I can update the hidden methods. Do you know which other ones there are? Also do we need to update these methods? I don't see Xcode complaining about deprecated methods so not sure what the value is for doing all this.

you can search with "accessibility(" in our project and all of those methods should be updated. I think we neeed a they were used only because of support of iOS 13 (they deprecated in iOS 15) and the new one were introduced in iOS 14.  Also, we can create a separate task for updating those if you want.

**Comment by JoshuaLai** [comment]
@palatter @vhuseinova-msft we are going to need to regression the accessibility too when we do the bug bash.

**Review by vhuseinova-msft — APPROVED** [review]

**Review by AmyL219 — APPROVED** [review]

**Pull request merged**
