### PR TITLE
[Bugfix] Fixed timer resources deallocation when a user leaves and rejoins a call quickly

### PR DESCRIPTION
**Pull request by vhuseinova-msft**
## Purpose

* ⁠Fixed an issue when a timer kept alive instance of InfoHeaderVM. This led to a crash when `CallingSDKWrapper` tried to create a new instance when another one wasn't deallocated yet.

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code
```
1) launch composite, tap on join call
2) tap `End call` button
3) tap `Start experience` button
4) tap `Join call` button
```

## What to Check
Verify that the following are valid
* The app is not crashed

### CODE REVIEW

**Review by Leah-Xia-Microsoft — DISMISSED** [review]
Tested on iPhone 13, iOS 16.0.2

**Review by kevinyulu — DISMISSED** [review]

**Review by kevinyulu — APPROVED** [review]

**Review by Leah-Xia-Microsoft — DISMISSED** [review]

**Comment by jpeng-ms** [comment]
hi @Leah-Xia-Microsoft were you able to reproduce the crash in develop/main without vik's changes?

**Comment by jpeng-ms** [comment]
hi, it seems I can still reproduce the crash: 
image
image
image

hope those helps

**Review by kevinyulu — DISMISSED** [review]

**Review by jimchou-dev — DISMISSED** [review]

**Review by emlynmac — DISMISSED** [review]

**Comment by vhuseinova-msft** [comment]
As per discussions with @jpeng-ms and @AmyL219, a spike task will be created to investigate CallingSDK joining/deallocation time that leads to a crash on John's device

**Comment by Leah-Xia-Microsoft** [comment]
> hi @Leah-Xia-Microsoft were you able to reproduce the crash in develop/main without vik's changes?

Sorry missed this message earlier. Yes I can reproduce it on develop and then cannot reproduce it on this branch on my physical device on iOS 16.

**Review by Leah-Xia-Microsoft — APPROVED** [review]

**Comment by Leah-Xia-Microsoft** [comment]
> As per discussions with @jpeng-ms and @AmyL219, a spike task will be created to investigate CallingSDK joining/deallocation time that leads to a crash on John's device

I think if we will have a different ticket dealing with the crash, we might want to change the description of this PR to only fixing the deloc performance.

**Review by kevinyulu — APPROVED** [review]

**Pull request merged**
