### PR TITLE
[Refactor] Avatar assets update

### PR DESCRIPTION
**Pull request by vhuseinova-msft**
## Purpose

* Updated avatar images to svg

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

## What to Check
Verify that the following are valid
* All avatars are available on the Settings page

### CODE REVIEW

**Review by jpeng-ms — APPROVED** [review]
looks good!

**Review by emlynmac — COMMENTED** [review]
My understanding is that SVG would be better if they are vector graphics, rather than PNGs.

Just looking inside the koala.svg, this is just a PNG wrapped in XML:

```
<image id="image0_2_6" x="10" y="10" width="12" height="12"
xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAVAUlEQVR4AexYRZgkvQ19squ7Z5YmjD9smJmZmXMKMzNdw8xM...<truncated for clarity>"
/>
```

**Comment by vhuseinova-msft** [comment]
> My understanding is that SVG would be better if they are vector graphics, rather than PNGs.
> 
> Just looking inside the koala.svg, this is just a PNG wrapped in XML:
> 
> ```
> <image id="image0_2_6" x="10" y="10" width="12" height="12"
> xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAVAUlEQVR4AexYRZgkvQ19squ7Z5YmjD9smJmZmXMKMzNdw8xM...<truncated for clarity>"
> />
> ```

Yes, you're right. But this is just for the demo app and won't have any influence on the actual library size. 

Also, all assets (but the app icons) are svg files and to be consistent, avatars images are changes to the svg files as well

**Review by emlynmac — APPROVED** [review]
I'd prefer to see proper vector assets, but as these are just for the demo app it does not affect the library.

**Pull request merged**
