### PR TITLE
[Calling][Feature] callkit enable/disable

### PR DESCRIPTION
**Pull request by iaulakh**
## Purpose

* enable callkit to manage calls, the callkit is a part of native sdk and will be enabled as per Contoso demand
* the UI library call on hold will be disabled on callkit enabled

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Pull request checklist

This PR has considered:
- [ ] Color Theming
- [ ] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] View Data Injection
- [ ] Demo App UI/UX update

## How to Test

* Open...
* Click on...

## What to Check

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| Screenshot or description before this change | Screenshot or description with this change |

### CODE REVIEW

**Comment by InquestApp-Admin** [comment]
Please merge and deploy the update to this ASAP! As a customer (Inquest Inspections platform for building inspections (https://www.inquestapp.com) , this feature is extremely important to us, and will be a huge reason for our use of both this library and ACS.   Thanks for your great work on this library!

**Comment by iaulakh** [comment]
@InquestApp-Admin would it be possible to know requirements and expectation from CallKit integration? The current support is only for outgoing call. We have incoming and 1 to N call is in progress.

**Comment by InquestApp-Admin** [comment]
@iaulakh   It is great to see progress on the CallKit integration. We need incoming call support as well for our platform, Inquest, which temporarily connects building inspectors with clients through our app. This feature is critical to enable real-time communication for emergencies or coordination without disclosing inspectors’ private numbers. Additionally, it ensures dispatchers can reach inspectors directly. Both incoming and outgoing calls are essential, mirroring traditional phone use within our secured app environment.

**Comment by iaulakh** [comment]
> Please merge and deploy the update to this ASAP! As a customer (Inquest Inspections platform for building inspections (https://www.inquestapp.com) , this feature is extremely important to us, and will be a huge reason for our use of both this library and ACS. Thanks for your great work on this library!

Hello everyone!!

We're more than happy to announce our newest update to the UI Library for native platforms – introducing the feature of one-on-one calls for Android and iOS! With this latest release, initiating a call is as simple as a tap, and recipients will be promptly alerted with a push notification to answer or decline the call.
For iOS, we've seamlessly integrated[ CallKit for a native iOS](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fcommunication-services%2Fhow-tos%2Fui-library-sdk%2Fcallkit&data=05%7C02%7Ciaulakh%40microsoft.com%7Ca3f54612cf114ce8167408dc106e7202%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638403313809315850%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PElFQRGjHObYD1oqxKV%2Betp9jHaslUoCEqX1lG7G1i8%3D&reserved=0) call experience. This means your calls will feel right at home on any iOS device, blending perfectly with the user's expectations and device behavior.

Our UI library has been meticulously designed to encapsulate an end-to-end experience that requires no complex coding. Immerse your users in a calling experience that's built on the best UI/UX practices, without the need to spend precious time developing the UI layer – we've got you covered.

This feature is currently in public preview, and we encourage you to dive into the documentation [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fazure%2Fcommunication-services%2Fhow-tos%2Fui-library-sdk%2Fone-to-one-calling%3Ftabs%3Dkotlin%26pivots%3Dplatform-android&data=05%7C02%7Ciaulakh%40microsoft.com%7Ca3f54612cf114ce8167408dc106e7202%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638403313809326169%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nIp1uTLPUZJ1CunEbmzMKugefvH9wfBnfRClqziNHSw%3D&reserved=0) to get started. Experience the ease of integrating high-quality calls into your application today!

Warm Regards!

UI Library team

**Pull request closed without merging**
