### PR TITLE
[Bugfix] Add mute status for accessibility label on participant grid.

### PR DESCRIPTION
**Pull request by palatter**
## Purpose
Add mute status for accessibility label on participant grid.

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Review by kevinyulu — DISMISSED** [review]
lgtm

**Review by vhuseinova-msft — CHANGES_REQUESTED** [review]
@palatter It looks like during some refactoring or development `not` operation was missed for 
`videoGridView
                        .accessibilityHidden(!viewModel.isVideoGridViewAccessibilityAvailable)`
 Now, the changes can't be tested as they are unavailable

**Comment by palatter** [comment]
> @palatter It looks like during some refactoring or development `not` operation was missed for `videoGridView .accessibilityHidden(!viewModel.isVideoGridViewAccessibilityAvailable)` Now, the changes can't be tested as they are unavailable

Good catch, fixed!

**Review by kevinyulu — APPROVED** [review]
lgtm

**Review by vhuseinova-msft — APPROVED** [review]
Looks good. Tested!

**Pull request merged**
