### PR TITLE
[Bugfix] Drawers dynamic update fix

### PR DESCRIPTION
**Pull request by vhuseinova-msft**
## Purpose

* Fix the issue when drawers aren't dynamically updated 

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

## What to Check
Verify that the following are valid
* The drawers can be dynamically updated
* Issue from [PR 297]( https://github.com/Azure/communication-ui-library-ios/pull/297) is still fixed

### CODE REVIEW

**Review by jimchou-dev — APPROVED** [review]
Tested LGTM

**Review by AmyL219 — APPROVED** [review]

**Comment by AmyL219** [comment]
We just revert the code, right?

**Comment by vhuseinova-msft** [comment]
> We just revert the code, right?

@AmyL219 , just part of it. I haven't reverted updated cell height calculations

**Comment by jpeng-ms** [comment]
Hi @jimchou-dev when you testing this, was this working for you? It appears broken on my side: 
IMG_824D66335A1A-1

**Comment by jimchou-dev** [comment]
> Hi @jimchou-dev when you testing this, was this working for you? It appears broken on my side: IMG_824D66335A1A-1

I didn't actually test the font size, only tested when user join/leave the drawer will update the number of cells

**Comment by vhuseinova-msft** [comment]
@jpeng-ms I have tested that when a user is just joined (for the large fonts) but maybe there is an edge case that I've missed

**Comment by jpeng-ms** [comment]
right, since it's a race condition (drawer resize called when drawer table view not fully loaded), we need to try it multiple times to reproduce it

**Pull request merged**
