### PR TITLE
[Bugfix] Solve the retain cycle between videoViewManager and Coordinate

### PR DESCRIPTION
**Pull request by AmyL219**
## Purpose

* The bug is the local video stream couldn't be displayed after ending a call with local video on
* The bug cause is the videoViewManager didn't get deallocated when composite is dismissed
* The videoViewManager's `didRenderFirstFrame` catch the coordiante's `ZoomableRenderView`
* The `ZoomableRenderView` catch the videoViewManager

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Test end a call with local video on, see if it's possible to see the grey local view when you restart a call

### CODE REVIEW

**Review by kevinyulu — DISMISSED** [review]
Tested the app turning the local video on and  joining a meeting with screenshare being presented. Re-join works as expected. local video shows.

**Comment by JoshuaLai** [comment]
`The bug cause is the videoViewManager didn't get allocated when composite is dismissed` @AmyL219 just to confirm you mean deallocated here right?

**Comment by AmyL219** [comment]
> `The bug cause is the videoViewManager didn't get allocated when composite is dismissed` @AmyL219 just to confirm you mean deallocated here right?

yeah, correct! Have fixed the word!

**Review by kevinyulu — APPROVED** [review]

**Review by jimchou-dev — APPROVED** [review]
Tested and can't reproduce the crash anymore, LGTM

**Review by JoshuaLai — APPROVED** [review]
Tested. LGTM

**Pull request merged**
